version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: orders_postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - orders_network
    restart: unless-stopped

networks:
  orders_network:
    driver: bridge

volumes:
  postgres_data:
